# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 22:55
from __future__ import unicode_literals

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'User',
                'indexes': [],
                'verbose_name_plural': 'Users',
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', apps.accounts.models.UserProxyManager()),
            ],
        ),
    ]
